/**
 * Secret and key generation, shared by both stacks.
 *
 * Shared deliberately rather than copied. The anon and service_role keys are
 * JWTs that PostgREST verifies against JWT_SECRET, so the signing must be byte
 * identical on both sides. Two implementations that drifted — a different claim
 * order, a different expiry, a padded base64 — would produce keys that look right
 * and fail to authenticate, with nothing but a 401 to go on.
 */

import { randomBytes, createHmac } from "node:crypto";

/**
 * Alphanumeric only. The Postgres password travels inside a URI
 * (postgres://authenticator:<pw>@127.0.0.1:5432/postgres) in both PostgREST
 * configurations, where '@', ':', '/' and '#' would each break parsing in a
 * different and confusing way.
 */
export const alnum = (bytes) =>
  randomBytes(bytes * 2).toString("base64").replace(/[^a-zA-Z0-9]/g, "").slice(0, bytes);

const b64url = (buf) =>
  Buffer.from(buf).toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");

export function signJwt(payload, secret) {
  const header = b64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const body = b64url(JSON.stringify(payload));
  const sig = b64url(createHmac("sha256", secret).update(`${header}.${body}`).digest());
  return `${header}.${body}.${sig}`;
}

/**
 * A Supabase-shaped role key. Ten years: these are machine-local keys on a
 * loopback-only stack, and an expiry short enough to matter would just mean the
 * client's reports stop one morning with a 401 nobody on site can diagnose.
 */
export function supabaseKey(role, secret) {
  const iat = Math.floor(Date.now() / 1000);
  return signJwt({ role, iss: "supabase", iat, exp: iat + 10 * 365 * 24 * 60 * 60 }, secret);
}

/** Serialise an env map with a header warning it must not be committed. */
export function renderEnvFile(values, extraNote = "") {
  const header = `# Generated by bootstrap.mjs — DO NOT COMMIT.
# Every value below is unique to this machine.${extraNote ? "\n# " + extraNote : ""}
`;
  return header + Object.entries(values).map(([k, v]) => `${k}=${v}`).join("\n") + "\n";
}
