#!/usr/bin/env node
/**
 * Generates this install's .env and renders volumes/api/kong.yml from it.
 *
 * Why per-install generation rather than shipping a .env:
 *
 * The obvious shortcut is to run `supabase start` from the CLI and hand the
 * client that. Its own startup banner warns why not — every service binds to
 * 0.0.0.0, and the printed keys (`sb_secret_N7UND0Ug...`) are compile-time
 * constants: identical on every machine running that CLI version, and published
 * in Supabase's own docs. On a shop PC that is the client's entire ledger, on
 * every network interface, behind a publicly known key.
 *
 * So: fresh POSTGRES_PASSWORD and JWT_SECRET per machine, with anon and
 * service_role keys signed by that secret. No secret in this repo, none shared
 * between two installs.
 *
 * Re-running is safe. Existing values in .env are preserved — only missing keys
 * are filled in — so this doubles as "repair my .env" without rotating secrets
 * that the backend and the desktop app are already configured with. Pass
 * --rotate to deliberately mint new ones (which invalidates every configured
 * client and requires a `docker compose down -v`, since role passwords are set
 * at first boot only).
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
// Shared with the native stack. The anon/service_role keys are JWTs verified
// against JWT_SECRET, so the signing has to be byte identical on both sides —
// two copies that drifted would mint keys that look right and 401.
import { alnum, supabaseKey } from "../../local-stack-shared/scripts/secrets.mjs";
import { readEnvFile } from "../../local-stack-shared/scripts/env.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const ENV_PATH = join(ROOT, ".env");
const KONG_TEMPLATE = join(ROOT, "volumes", "api", "kong.template.yml");
const KONG_OUT = join(ROOT, "volumes", "api", "kong.yml");

const rotate = process.argv.includes("--rotate");

const existing = readEnvFile(ENV_PATH);
const generated = [];

function ensure(key, makeValue) {
  if (!rotate && existing[key]) return existing[key];
  const value = makeValue();
  generated.push(key);
  return value;
}

const jwtSecret = ensure("JWT_SECRET", () => alnum(48));
// If the secret was just rotated the old keys no longer verify, so they must go
// too — otherwise Kong would hand PostgREST a key it rejects with a 401 that
// looks like a config error rather than a stale key.
const secretChanged = generated.includes("JWT_SECRET");
const anonKey = secretChanged || !existing.ANON_KEY ? supabaseKey("anon", jwtSecret) : existing.ANON_KEY;
const serviceKey =
  secretChanged || !existing.SERVICE_ROLE_KEY
    ? supabaseKey("service_role", jwtSecret)
    : existing.SERVICE_ROLE_KEY;
if (!generated.includes("ANON_KEY") && anonKey !== existing.ANON_KEY) generated.push("ANON_KEY");
if (!generated.includes("SERVICE_ROLE_KEY") && serviceKey !== existing.SERVICE_ROLE_KEY) {
  generated.push("SERVICE_ROLE_KEY");
}

const env = {
  POSTGRES_DB: existing.POSTGRES_DB || "postgres",
  POSTGRES_PASSWORD: ensure("POSTGRES_PASSWORD", () => alnum(32)),
  JWT_SECRET: jwtSecret,
  JWT_EXPIRY: existing.JWT_EXPIRY || "3600",
  ANON_KEY: anonKey,
  SERVICE_ROLE_KEY: serviceKey,
  // Same ports the Supabase CLI uses, so anything written against a CLI-based
  // local stack keeps working unchanged.
  KONG_HTTP_PORT: existing.KONG_HTTP_PORT || "54321",
  POSTGRES_PORT: existing.POSTGRES_PORT || "54322",
  STUDIO_PORT: existing.STUDIO_PORT || "54323",
  SUPABASE_PUBLIC_URL: existing.SUPABASE_PUBLIC_URL || `http://127.0.0.1:${existing.KONG_HTTP_PORT || "54321"}`,
  STUDIO_DEFAULT_ORGANIZATION: existing.STUDIO_DEFAULT_ORGANIZATION || "TallyBridge",
  STUDIO_DEFAULT_PROJECT: existing.STUDIO_DEFAULT_PROJECT || "TallyBridge Local",
  DASHBOARD_USERNAME: existing.DASHBOARD_USERNAME || "supabase",
  DASHBOARD_PASSWORD: ensure("DASHBOARD_PASSWORD", () => alnum(20)),
};

const header = `# Generated by scripts/bootstrap.mjs — DO NOT COMMIT.
# Every value below is unique to this machine. Regenerate with:
#     node scripts/bootstrap.mjs --rotate
# Rotating requires 'docker compose down -v' as well: role passwords are applied
# by volumes/db/init/00-roles.sql, which only runs on an empty data volume.
`;

writeFileSync(
  ENV_PATH,
  header + Object.entries(env).map(([k, v]) => `${k}=${v}`).join("\n") + "\n",
  "utf8",
);

// ── kong.yml ─────────────────────────────────────────────────────────────────
// The upstream compose file keeps env placeholders in kong.yml and substitutes
// them at container start with
//     bash -c 'eval "echo \\"$$(cat ~/temp.yml)\\"" > ~/kong.yml && ...'
// An `eval` over a config file that holds secrets, where one stray backtick in a
// password is remote code execution in the gateway. Rendering the file here
// instead costs nothing and lets the container run its stock entrypoint.
if (!existsSync(KONG_TEMPLATE)) {
  console.error(`missing template: ${KONG_TEMPLATE}`);
  process.exit(1);
}
mkdirSync(dirname(KONG_OUT), { recursive: true });
const kong = readFileSync(KONG_TEMPLATE, "utf8")
  .replaceAll("${ANON_KEY}", env.ANON_KEY)
  .replaceAll("${SERVICE_ROLE_KEY}", env.SERVICE_ROLE_KEY)
  .replaceAll("${DASHBOARD_USERNAME}", env.DASHBOARD_USERNAME)
  .replaceAll("${DASHBOARD_PASSWORD}", env.DASHBOARD_PASSWORD);
writeFileSync(KONG_OUT, kong, "utf8");

console.log(`.env       ${existsSync(ENV_PATH) ? "updated" : "created"}  ${ENV_PATH}`);
console.log(`kong.yml   rendered  ${KONG_OUT}`);
console.log(generated.length ? `generated: ${generated.join(", ")}` : "generated: nothing (all values already present)");
